apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app-sga
  labels:
    app: netflix-app-shubham
spec:
  replicas: 4
  selector:
    matchLabels:
      app: netflix-app-shubham
  template:
    metadata:
      labels:
        app: netflix-app-shubham
    spec:
      containers:
      - name: netflix-app-shubham
        image: shubhambct/netflix:latest
        ports:
        - containerPort: 80
#
