apiVersion: v1
kind: Service
metadata:
  name: netflix-app-shubham
  labels:
    app: netflix-app-shubham
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: netflix-app-shubham
